messages:
  noPermission: "<dark_red>You dont have permission to use this command!"
  disablePlace: "<dark_red>You cannot place this item in backpack!"
  disableCraft: "<dark_red>You cannot craft the backpack this way!"
  giveMessage: "<gold>{player} <green>gave you <gold>{backpack}"
  cancelOpen: "<dark_red>You cannot open stacked backpacks!"
  #The disableCraft runs when player tries to craft the backpack
  #while holding shift.
  #Made this to prevent duping items.

putBackpacksIntoShulkers: false

soundLevelOfBackpacks: 0.5
pitchLevelOfBackpacks: 1

slotsLimit: '<red>Slots Limit!'

showContents: true

backpackLore:
- '<gray>A special portable bag with'
- '<gold>{slotsAmount} <gray>slots!'


emptyBackpack: '<red>Backpack is empty!'

displayItemInLore: '<green>{number}x {item_name}'
#when there is more than 5 items in the backpack
#it will display the first 5 items and the amount of other items (summed)
otherItemsInLore: '<gray>and other <gold>{amount} <gray>items!'